config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :motorista do
    collection do
      get 'buscar_motorista'
      get 'home'
    end
  end

  get 'rotas/buscar_por_placa', to: 'rota#buscar_por_onibus', as: 'buscar_por_onibus'
  get 'rotas/resultados_por_placa', to: 'rota#buscar_por_onibus_resultados', as: 'buscar_por_onibus_resultados'
  get 'onibuses/busca', to: 'onibuses#search', as: 'buscar_onibus'
  resources :onibuses do
    collection do
      get 'home'
    end
  end
  resources :rota do
    collection do
      get 'home'
    end
  end

end

app/controllers/motorista_controller.rb
class MotoristaController < ApplicationController
  before_action :set_motoristum, only: %i[ show edit update destroy ]

  def home
  end
  # GET /motorista or /motorista.json
  def index
    @motorista = Motoristum.all
  end

  # GET /motorista/1 or /motorista/1.json
  def show
    @motorista = Motoristum.find(params[:id])
  end

  # GET /motorista/new
  def new
    @motoristum = Motoristum.new
  end

  # GET /motorista/1/edit
  def edit
  end

  # POST /motorista or /motorista.json
  def create
    @motoristum = Motoristum.new(motoristum_params)

    respond_to do |format|
      if @motoristum.save
        format.html { redirect_to motoristum_url(@motoristum), notice: "Motoristum was successfully created." }
        format.json { render :show, status: :created, location: @motoristum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motoristum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motorista/1 or /motorista/1.json
  def update
    respond_to do |format|
      if @motoristum.update(motoristum_params)
        format.html { redirect_to motoristum_url(@motoristum), notice: "Motoristum was successfully updated." }
        format.json { render :show, status: :ok, location: @motoristum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motoristum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motorista/1 or /motorista/1.json
  def destroy
    @motoristum.destroy

    respond_to do |format|
      format.html { redirect_to motorista_url, notice: "Motoristum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buscar_motorista
    query = params[:query]
    @results = Motoristum.where("nome LIKE  ? OR cpf = ? OR email = ?", "%#{query}%", query, query)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motoristum
      @motoristum = Motoristum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motoristum_params
      params.require(:motoristum).permit(:nome, :cpf, :email, :telefone, :cnh)
    end
end

app/helpers/motorista_helper.rb
module MotoristaHelper
end

app/views/motorista/_form.html.erb
<%= form_with(model: motoristum) do |form| %>
  <% if motoristum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motoristum.errors.count, "error") %> prohibited this motoristum from being saved:</h2>

      <ul>
        <% motoristum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :cnh, style: "display: block" %>
    <%= form.text_field :cnh %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/motorista/_motoristum.html.erb
<div id="<%= dom_id motoristum %>">
  <p>
    <strong>Nome:</strong>
    <%= motoristum.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= motoristum.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= motoristum.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= motoristum.telefone %>
  </p>

  <p>
    <strong>Cnh:</strong>
    <%= motoristum.cnh %>
  </p>

</div>

app/views/motorista/buscar_motorista.erb
<h1>Buscar Motoristas</h1>

<%= form_tag buscar_motorista_motorista_path, method: :get do %>
  <%= label_tag :query, "Digite o nome, CPF ou email do motorista:" %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Buscar" %>
<% end %>

<% if @results.any? %>
  <h2>Resultados da Busca:</h2>
  <% @results.each do |motoristum| %>
    <%= render motoristum %>
    <p>
      <%= link_to "Show this motoristum", motoristum %>
    </p>
  <% end %>
<% else %>
  <p>Nenhum motorista encontrado.</p>
<% end %>

<%= link_to "Back to Home Motorista", home_motorista_url %>

app/views/motorista/edit.html.erb
<h1>Editing motoristum</h1>

<%= render "form", motoristum: @motoristum %>

<br>

<div>
  <%= link_to "Show this motoristum", @motoristum %> |
  <%= link_to "Back to motorista", motorista_path %>
</div>

app/views/motorista/home.html.erb
<style>
  body{
      background-image: url('/app/assets/images/searc.jpg');
  }

</style>

<h1>Home Motorista</h1>

<ul class="menu">
  <li><%=     link_to "Cadastrar Motorista", new_motoristum_path %> </li>
  <li><%=     link_to "Listar Motoristas", motorista_path %> </li>
  <li><%=     link_to "Buscar Motoristas", buscar_motorista_motorista_path %> </li>
</ul>

<div>
  <%= link_to "Voltar para o inicio", "/" %>
</div>

app/views/motorista/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Motorista</h1>

<div id="motorista">
  <% @motorista.each do |motoristum| %>
    <%= render motoristum %>
    <p>
      <%= link_to "Show this motoristum", motoristum %>
    </p>
  <% end %>
</div>

<%= link_to "New motoristum", new_motoristum_path %> |
<%= link_to "Back to Home Motorista", home_motorista_url %>

app/views/motorista/new.html.erb
<h1>Novo Motorista</h1>

<%= render "form", motoristum: @motoristum %>

<br>

<div>
  <%= link_to "Back to motoristas", motorista_path %> |
  <%= link_to "Back to Home Motorista", home_motorista_url %>

</div>

app/views/motorista/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @motoristum %>

<div>
  <%= link_to "Edit this motoristum", edit_motoristum_path(@motoristum) %> |
  <%= link_to "Back to motorista", motorista_path %> |
  <%= link_to "Back to Home Motorista", home_motorista_url %>


  <%= button_to "Destroy this motoristum", @motoristum, method: :delete %>

</div>