config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :motorista do
    collection do
      get 'buscar_motorista'
      get 'home'
    end
  end

  get 'rotas/buscar_por_placa', to: 'rota#buscar_por_onibus', as: 'buscar_por_onibus'
  get 'rotas/resultados_por_placa', to: 'rota#buscar_por_onibus_resultados', as: 'buscar_por_onibus_resultados'
  get 'onibuses/busca', to: 'onibuses#search', as: 'buscar_onibus'
  resources :onibuses do
    collection do
      get 'home'
    end
  end
  resources :rota do
    collection do
      get 'home'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render 'layouts/account_links' %>

<!DOCTYPE html>
<html>
<head>
  <style>
      body {
          background-image: url("<%= image_path('searc.jpg') %>");
          background-position: center;
          background-size: cover;
          background-repeat: no-repeat;
          background-attachment: fixed; /* Mantém o fundo fixo enquanto a página é rolada */
          margin: 0;
          padding: 0;
          font-family: Arial, sans-serif;
      }
      .content-box {
          width: 400px;
          background-color: #21232d;
          border-radius: 10px;
          padding: 30px;
          margin: 50px auto;
          color: white;
          text-align: center;
      }

      .menu {
          list-style-type: none;
          padding: 0;
      }

      .menu li {
          margin-bottom: 15px;
      }

      .menu a {
          color: white;
          text-decoration: none;
          font-size: 18px;
      }

      h1 {
          font-size: 28px;
          border-bottom: 2px solid lightgray;
          padding-bottom: 10px;
          margin-bottom: 20px;
      }

      h2 {
          font-size: 24px;
          margin-bottom: 20px;
      }
  </style>

</head>
<body>
<div class="content-box">
  <h1>Funcionalidades</h1>
  <ul class="menu">
    <li><a href="<%= home_motorista_url %>">Motorista</a></li>
    <li><a href="<%= home_onibuses_url %>">Ônibus</a></li>
    <li><a href="<%= home_rota_url %>">Rotas</a></li>
  </ul>
</div>
</body>
</html>


<%= render 'layouts/footer' %>