config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :motorista do
    collection do
      get 'buscar_motorista'
      get 'home'
    end
  end

  get 'rotas/buscar_por_placa', to: 'rota#buscar_por_onibus', as: 'buscar_por_onibus'
  get 'rotas/resultados_por_placa', to: 'rota#buscar_por_onibus_resultados', as: 'buscar_por_onibus_resultados'
  get 'onibuses/busca', to: 'onibuses#search', as: 'buscar_onibus'
  resources :onibuses do
    collection do
      get 'home'
    end
  end
  resources :rota do
    collection do
      get 'home'
    end
  end

end

app/controllers/rota_controller.rb
class RotaController < ApplicationController
  before_action :set_rotum, only: %i[ show edit update destroy ]

  def home
  end

  def index
    @rota = Rotum.all
  end

  def show
  end

  def new
    @rotum = Rotum.new
    list_onibus_and_motorista
  end

  def edit
  end

  def create
    @rotum = Rotum.new(rotum_params)
    if @rotum.save
      show_message_and_handle_response("Rotum was successfully created.", rotum_url(@rotum))
    else
      show_message_and_handle_response(nil, nil, @rotum.errors, :new)
      list_onibus_and_motorista
    end
  end

  def update
    if @rotum.update(rotum_params)
      show_message_and_handle_response("Rotum was successfully updated.", rotum_url(@rotum))
    else
      show_message_and_handle_response(nil, nil, @rotum.errors, :edit)
    end
  end

  def show_message_and_handle_response(message, redirect_path, errors = nil, render_path = nil)
    respond_to do |format|
      if errors.nil?
        format.html { redirect_to redirect_path, notice: message }
        format.json { render json: { message: message }, status: :ok }
      else
        list_onibus_and_motorista
        format.html { render render_path, status: :unprocessable_entity }
        format.json { render json: { errors: errors }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rotum.destroy
    respond_to do |format|
      format.html { redirect_to rota_url, notice: "Rotum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buscar_por_onibus
    @placas_onibus = Onibus.pluck(:placa)
    @rotas = Rotum.joins(:onibus).where("onibuses.placa = ?", params[:placa])
    render 'busca_por_onibus'
  end

  def list_onibus_and_motorista
    @onibus = Onibus.all
    @motorista = Motoristum.all
  end

  private
    def set_rotum
      @rotum = Rotum.find_by(id: params[:id])
      list_onibus_and_motorista
    end

    def rotum_params
      params.require(:rotum).permit(:nome, :valor, :distancia, :duracao, :inicio, :fim, :origem, :destino, :onibus_id, :motoristum_id)
    end
end

app/helpers/rota_helper.rb
module RotaHelper
end

app/views/rota/_form.html.erb
<%= form_with(model: rotum) do |form| %>
  <% if rotum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rotum.errors.count, "error") %> prohibited this rotum from being saved:</h2>

      <ul>
        <% rotum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :distancia, style: "display: block" %>
    <%= form.text_field :distancia %>
  </div>

  <div>
    <%= form.label :duracao, style: "display: block" %>
    <%= form.text_field :duracao %>
  </div>

  <div>
    <%= form.label :inicio, style: "display: block" %>
    <%= form.time_field :inicio %>
  </div>

  <div>
    <%= form.label :fim, style: "display: block" %>
    <%= form.time_field :fim %>
  </div>

  <div>
    <%= form.label :origem, style: "display: block" %>
    <%= form.text_field :origem %>
  </div>

  <div>
    <%= form.label :destino, style: "display: block" %>
    <%= form.text_field :destino %>
  </div>

  <div>
    <%= form.label :onibus_id, style: "display: block" %>
    <%= form.collection_select :onibus_id, @onibus, :id, :placa, prompt: 'Selecione um ônibus'%>
  </div>

  <div>
    <%= form.label :motoristum_id, style: "displaY: block" %>
    <%= form.collection_select :motoristum_id, @motorista, :id, :nome, prompt: 'Selecione um Motorista'%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rota/_rotum.html.erb
<div id="<%= dom_id rotum %>">
  <p>
    <strong>Nome:</strong>
    <%= rotum.nome %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= rotum.valor %>
  </p>

  <p>
    <strong>Distancia:</strong>
    <%= rotum.distancia %>
  </p>

  <p>
    <strong>Duracao:</strong>
    <%= rotum.duracao %>
  </p>

  <p>
    <strong>Inicio:</strong>
    <%= rotum.inicio %>
  </p>

  <p>
    <strong>Fim:</strong>
    <%= rotum.fim %>
  </p>

  <p>
    <strong>Origem:</strong>
    <%= rotum.origem %>
  </p>

  <p>
    <strong>Destino:</strong>
    <%= rotum.destino %>
  </p>

  <p>
    <strong>Onibus:</strong>
    <%= rotum.onibus_id %>
  </p>

</div>

app/views/rota/busca_por_onibus.erb
<h1>Buscar Rotas por Placa do Ônibus</h1>

<%= form_tag(buscar_por_onibus_path, method: :get) do %>
  <div class="field">
    <%= label_tag :placa, 'Placa do Ônibus:' %>
    <%= select_tag :placa, options_for_select(@placas_onibus) %>
  </div>

  <div class="actions">
    <%= submit_tag 'Buscar' %>
  </div>
<% end %>

<h1>Resultados da busca por placa do ônibus</h1>

<% if @rotas.present? %>
  <h2>Resultados:</h2>
  <% @rotas.each do |rota| %>
    <p>
      Nome: <%= rota.nome %><br>
      Valor: <%= rota.valor %><br>
      Distância: <%= rota.distancia %><br>
      <!-- ... outros campos ... -->
    </p>
  <% end %>
<% else %>
  <p>Nenhum resultado encontrado.</p>
<% end %>

<%= link_to "Back to Home Rota", home_rota_url %>

app/views/rota/edit.html.erb
<h1>Editing rotum</h1>

<%= render "form", rotum: @rotum %>

<br>

<div>
  <%= link_to "Show this rotum", @rotum %> |
  <%= link_to "Back to rota", rota_path %>
</div>

app/views/rota/home.html.erb
<h1>Home Rotas</h1>

<ul class="menu">
  <li><%= link_to "Cadastrar Rota", new_rotum_path %> </li>
  <li><%= link_to "Listar Rotas", rota_path %> </li>
  <li><%= link_to "Buscar Rotas", buscar_por_onibus_path %> </li>
</ul>

<div>
  <%= link_to "Voltar para o inicio", "/" %>
</div>

app/views/rota/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rota</h1>

<div id="rota">
  <% @rota.each do |rotum| %>
    <%= render rotum %>
    <p>
      <%= link_to "Show this rotum", rotum %>
    </p>
  <% end %>
</div>

<%= link_to "New rotum", new_rotum_path %> |

<%= link_to "Back to Home Rota", home_rota_url %>

app/views/rota/new.html.erb
<h1>New rotum</h1>

<%= render "form", rotum: @rotum %>

<br>

<div>
  <%= link_to "Back to rota", rota_path %> |
  <%= link_to "Back to Home Rota", home_rota_url %>
</div>

app/views/rota/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rotum %>

<div>
  <%= link_to "Edit this rotum", edit_rotum_path(@rotum) %> |
  <%= link_to "Back to rota", rota_path %> |
  <%= link_to "Back to Home Rota", home_rota_url %>

  <%= button_to "Destroy this rotum", @rotum, method: :delete %>
</div>