config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :motorista do
    collection do
      get 'buscar_motorista'
      get 'home'
    end
  end

  get 'rotas/buscar_por_placa', to: 'rota#buscar_por_onibus', as: 'buscar_por_onibus'
  get 'rotas/resultados_por_placa', to: 'rota#buscar_por_onibus_resultados', as: 'buscar_por_onibus_resultados'
  get 'onibuses/busca', to: 'onibuses#search', as: 'buscar_onibus'
  resources :onibuses do
    collection do
      get 'home'
    end
  end
  resources :rota do
    collection do
      get 'home'
    end
  end

end

app/controllers/onibuses_controller.rb
class OnibusesController < ApplicationController
  before_action :set_onibus, only: %i[ show edit update destroy ]

  def home
  end
  # GET /onibuses or /onibuses.json
  def index
    @onibuses = Onibus.all
  end

  # GET /onibuses/1 or /onibuses/1.json
  def show
    @onibus = Onibus.find(params[:id])
  end

  # GET /onibuses/new
  def new
    @onibus = Onibus.new
  end

  # GET /onibuses/1/edit
  def edit
  end

  # POST /onibuses or /onibuses.json
  def create
    @onibus = Onibus.new(onibus_params)

    respond_to do |format|
      if @onibus.save
        format.html { redirect_to onibus_url(@onibus), notice: "Onibus was successfully created." }
        format.json { render :show, status: :created, location: @onibus }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onibuses/1 or /onibuses/1.json
  def update
    respond_to do |format|
      if @onibus.update(onibus_params)
        format.html { redirect_to onibus_url(@onibus), notice: "Onibus was successfully updated." }
        format.json { render :show, status: :ok, location: @onibus }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onibuses/1 or /onibuses/1.json
  def destroy
    @onibus.destroy

    respond_to do |format|
      format.html { redirect_to onibuses_url, notice: "Onibus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = []
    data = params[:data]
    @param = params[:param]
    case @param
      when "Placa" then search_by_placa(data)
      when "Chassi" then search_by_chassi(data)
      when "Modelo" then search_by_modelo(data)
    end
    render 'busca'
  end

  private

    def search_by_placa(data)
      @results = Onibus.where("onibuses.placa LIKE ?", "%#{data}%")
    end

    def search_by_chassi(data)
      @results = Onibus.where("onibuses.chassi LIKE ?", "%#{data}%")
    end

    def search_by_modelo(data)
      @results = Onibus.where("onibuses.modelo LIKE ?", "%#{data}%")
    end

    def set_onibus
      @onibus = Onibus.find(params[:id])
    end

    def onibus_params
      params.require(:onibus).permit(:placa, :chassi, :modelo, :capacidade, :status)
    end

end

app/helpers/onibuses_helper.rb
module OnibusesHelper
end

app/views/onibuses/_form.html.erb
<%= form_with(model: onibus) do |form| %>
  <% if onibus.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(onibus.errors.count, "error") %> prohibited this onibus from being saved:</h2>

      <ul>
        <% onibus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :placa, style: "display: block" %>
    <%= form.text_field :placa %>
  </div>

  <div>
    <%= form.label :chassi, style: "display: block" %>
    <%= form.text_field :chassi %>
  </div>

  <div>
    <%= form.label :modelo, style: "display: block" %>
    <%= form.text_field :modelo %>
  </div>

  <div>
    <%= form.label :capacidade, style: "display: block" %>
    <%= form.number_field :capacidade %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, ["em operação", "indisponível", "em manutenção"] %>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/onibuses/_onibus.html.erb
<div id="<%= dom_id onibus %>">
  <p>
    <strong>Placa:</strong>
    <%= onibus.placa %>
  </p>

  <p>
    <strong>Chassi:</strong>
    <%= onibus.chassi %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= onibus.modelo %>
  </p>

  <p>
    <strong>Capacidade:</strong>
    <%= onibus.capacidade %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= onibus.status %>
  </p>

</div>

app/views/onibuses/busca.html.erb
<p style="color: green"><%= notice %></p>

<h1>Onibus</h1>

<%= form_tag buscar_onibus_path, method: :get do %>
  <%= label_tag :data, "Busca:" %>
  <%= text_field_tag :data, params[:data] %>
  <br><br>
  <%= label_tag 'param_Chassi', "Chassi:" %>
  <%= radio_button_tag(:param, "Chassi", checked = true) %>
  <%= label_tag 'param_Modelo', "Modelo:" %>
  <%= radio_button_tag(:param, "Modelo") %>
  <%= label_tag 'param_Placa', "Placa:" %>
  <%= radio_button_tag(:param, "Placa") %>
  <br><br>
  <%= submit_tag "Buscar" %>
<% end %>


<% if @results.any? %>
  <h2>Resultados da Busca por <%=@param%>:</h2>
  <div id="onibuses">
  <% @results.each do |onibus| %>
    <%= render onibus %>
    <p>
      <%= link_to "Show this onibus", onibus %>
    </p>
  <% end %>
</div>
<% else %>
  <p>Nenhum onibus encontrado.</p>
<% end %>

<%= link_to "Back to Home Onibus", home_onibuses_url %>

app/views/onibuses/edit.html.erb
<h1>Editing onibus</h1>

<%= render "form", onibus: @onibus %>

<br>

<div>
  <%= link_to "Show this onibus", @onibus %> |
  <%= link_to "Back to onibuses", onibuses_path %>
</div>

app/views/onibuses/home.html.erb
<h1>Home Onibus</h1>

<ul class="menu">
  <li><%= link_to "Cadastrar Ônibus", new_onibus_path %> </li>
  <li><%= link_to "Listar Ônibus", onibuses_path %> </li>
  <li><%= link_to "Buscar Onibus",  buscar_onibus_path %> </li>


</ul>

<div>
  <%= link_to "Voltar para o inicio", "/" %>
</div>

app/views/onibuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Onibuses</h1>

<div id="onibuses">
  <% @onibuses.each do |onibus| %>
    <%= render onibus %>
    <p>
      <%= link_to "Show this onibus", onibus %>
    </p>
  <% end %>
</div>

<%= link_to "New onibus", new_onibus_path %> |
<%= link_to "Back to Home Onibus", home_onibuses_url %>

app/views/onibuses/new.html.erb
<h1>New onibus</h1>

<%= render "form", onibus: @onibus %>

<br>

<div>
  <%= link_to "Back to onibuses", onibuses_path %> |
  <%= link_to "Back to Home Onibus", home_onibuses_url %>
</div>

app/views/onibuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @onibus %>

<div>
  <%= link_to "Edit this onibus", edit_onibus_path(@onibus) %> |
  <%= link_to "Back to onibuses", onibuses_path %> |
  <%= link_to "Back to Home Onibus", home_onibuses_url %>

  <%= button_to "Destroy this onibus", @onibus, method: :delete %>
</div>